# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/bntha/Desktop/ZedBoard_Tuturial/project_first_zynq_design/project_first_zynq_design.srcs/sources_1/bd/first_zynq_system/ip/first_zynq_system_rst_ps7_0_100M_0/first_zynq_system_rst_ps7_0_100M_0.xci
# IP: The module: 'first_zynq_system_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/bntha/Desktop/ZedBoard_Tuturial/project_first_zynq_design/project_first_zynq_design.srcs/sources_1/bd/first_zynq_system/ip/first_zynq_system_rst_ps7_0_100M_0/first_zynq_system_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'first_zynq_system_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/bntha/Desktop/ZedBoard_Tuturial/project_first_zynq_design/project_first_zynq_design.srcs/sources_1/bd/first_zynq_system/ip/first_zynq_system_rst_ps7_0_100M_0/first_zynq_system_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'first_zynq_system_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/bntha/Desktop/ZedBoard_Tuturial/project_first_zynq_design/project_first_zynq_design.srcs/sources_1/bd/first_zynq_system/ip/first_zynq_system_rst_ps7_0_100M_0/first_zynq_system_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'first_zynq_system_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/bntha/Desktop/ZedBoard_Tuturial/project_first_zynq_design/project_first_zynq_design.srcs/sources_1/bd/first_zynq_system/ip/first_zynq_system_rst_ps7_0_100M_0/first_zynq_system_rst_ps7_0_100M_0.xci
# IP: The module: 'first_zynq_system_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/bntha/Desktop/ZedBoard_Tuturial/project_first_zynq_design/project_first_zynq_design.srcs/sources_1/bd/first_zynq_system/ip/first_zynq_system_rst_ps7_0_100M_0/first_zynq_system_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'first_zynq_system_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/bntha/Desktop/ZedBoard_Tuturial/project_first_zynq_design/project_first_zynq_design.srcs/sources_1/bd/first_zynq_system/ip/first_zynq_system_rst_ps7_0_100M_0/first_zynq_system_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'first_zynq_system_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/bntha/Desktop/ZedBoard_Tuturial/project_first_zynq_design/project_first_zynq_design.srcs/sources_1/bd/first_zynq_system/ip/first_zynq_system_rst_ps7_0_100M_0/first_zynq_system_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'first_zynq_system_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
