# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/adventures_with_ip.xdc

# Block Designs: bd/ip_design/ip_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ip_design || ORIG_REF_NAME==ip_design} -quiet] -quiet

# IP: bd/ip_design/ip/ip_design_processing_system7_0_0/ip_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ip_design_processing_system7_0_0 || ORIG_REF_NAME==ip_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/ip_design/ip/ip_design_led_controller_0_0/ip_design_led_controller_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ip_design_led_controller_0_0 || ORIG_REF_NAME==ip_design_led_controller_0_0} -quiet] -quiet

# IP: bd/ip_design/ip/ip_design_nco_0_0/ip_design_nco_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ip_design_nco_0_0 || ORIG_REF_NAME==ip_design_nco_0_0} -quiet] -quiet

# IP: bd/ip_design/ip/ip_design_lms_pcore_0_0/ip_design_lms_pcore_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ip_design_lms_pcore_0_0 || ORIG_REF_NAME==ip_design_lms_pcore_0_0} -quiet] -quiet

# IP: bd/ip_design/ip/ip_design_ps7_0_axi_periph_0/ip_design_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ip_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==ip_design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/ip_design/ip/ip_design_rst_ps7_0_100M_0/ip_design_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ip_design_rst_ps7_0_100M_0 || ORIG_REF_NAME==ip_design_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/ip_design/ip/ip_design_xbar_0/ip_design_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ip_design_xbar_0 || ORIG_REF_NAME==ip_design_xbar_0} -quiet] -quiet

# IP: bd/ip_design/ip/ip_design_axi_gpio_0_0/ip_design_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ip_design_axi_gpio_0_0 || ORIG_REF_NAME==ip_design_axi_gpio_0_0} -quiet] -quiet

# IP: bd/ip_design/ip/ip_design_zed_audio_ctrl_0_0/ip_design_zed_audio_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ip_design_zed_audio_ctrl_0_0 || ORIG_REF_NAME==ip_design_zed_audio_ctrl_0_0} -quiet] -quiet

# IP: bd/ip_design/ip/ip_design_clk_wiz_0_0/ip_design_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ip_design_clk_wiz_0_0 || ORIG_REF_NAME==ip_design_clk_wiz_0_0} -quiet] -quiet

# IP: bd/ip_design/ip/ip_design_auto_pc_0/ip_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ip_design_auto_pc_0 || ORIG_REF_NAME==ip_design_auto_pc_0} -quiet] -quiet

# XDC: bd/ip_design/ip_design_ooc.xdc
