# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/led_controller/led_constraints.xdc

# Block Designs: bd/led_test_system/led_test_system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==led_test_system || ORIG_REF_NAME==led_test_system} -quiet] -quiet

# IP: bd/led_test_system/ip/led_test_system_processing_system7_0_0/led_test_system_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==led_test_system_processing_system7_0_0 || ORIG_REF_NAME==led_test_system_processing_system7_0_0} -quiet] -quiet

# IP: bd/led_test_system/ip/led_test_system_led_controller_0_0/led_test_system_led_controller_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==led_test_system_led_controller_0_0 || ORIG_REF_NAME==led_test_system_led_controller_0_0} -quiet] -quiet

# IP: bd/led_test_system/ip/led_test_system_ps7_0_axi_periph_0/led_test_system_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==led_test_system_ps7_0_axi_periph_0 || ORIG_REF_NAME==led_test_system_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/led_test_system/ip/led_test_system_rst_ps7_0_100M_0/led_test_system_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==led_test_system_rst_ps7_0_100M_0 || ORIG_REF_NAME==led_test_system_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/led_test_system/ip/led_test_system_auto_pc_0/led_test_system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==led_test_system_auto_pc_0 || ORIG_REF_NAME==led_test_system_auto_pc_0} -quiet] -quiet

# XDC: bd/led_test_system/led_test_system_ooc.xdc
